### ISSUE TITLE
Other .net projects for PocketBase 

### ISSUE THREAD

**Issue by iluvadev** [Naquino14/PocketbaseNET#1]
Hi! 
You can see other .net projects related with PocketBase, for inspiration, to use them or to colaborate with ;)
- Sdk: https://github.com/PRCV1/pocketbase-csharp-sdk

- ORM: https://github.com/iluvadev/PocketBaseClient-csharp

👍

**Comment by Naquino14** [comment]
@iluvadev Hi there! I will definitely check those out. Thank you!
